const PRIMARY_COLOR = "#0F0F0F";
const SECUNDARY_COLOR = "#202020";
const BACKGROUND_COLOR = "#000000";
const BUTTON_COLOR = "#2563eb";
const BUTTON_TEXT_COLOR = "#FFFFFF";
const TEXT_COLOR = "#FFFFFF";

export default {
  // Colors
  PRIMARY_COLOR,
  SECUNDARY_COLOR,
  BACKGROUND_COLOR,
  BUTTON_COLOR,
  BUTTON_TEXT_COLOR,
  TEXT_COLOR,
};
